#!/usr/bin/env python3

import os
import shutil

shutil.rmtree('user', ignore_errors=True)

with open('files-user') as f:
    files = [fn for fn in f.read().splitlines() if fn.strip() and not fn.startswith('#')]

for fn in files:
    print(fn)
    fn_abs = os.path.expanduser(fn)
    backup_dir = 'user' + os.path.dirname(fn[1:])
    try: os.makedirs(backup_dir)
    except: pass
    shutil.copy(fn_abs, backup_dir)
