#!/usr/bin/env python3

import os
import shutil

shutil.rmtree('system', ignore_errors=True)

with open('files-system') as f:
    files = [fn for fn in f.read().splitlines() if fn.strip() and not fn.startswith('#')]

for fn in files:
    print(fn)
    backup_dir = 'system' + os.path.dirname(fn)
    try: os.makedirs(backup_dir)
    except: pass
    shutil.copy(fn, backup_dir)
